name: osio-bridge
version: 0.0.1
summary: OpenSensors.io sensor gateway
description: Connect sensors to OpenSensors.io via a IOT gateway running snappy
icon: icon.png

apps:
  sensor-temp-pcsensor:
    command: usr/local/bin/pcsensor
  osio-bridge:
    command: bin/node bin/osio-bridge
    daemon: simple
    uses: [cloud-comm]

uses:
  cloud-comm:
    type: migration-skill
    caps: [network-client]

parts:
  pcsensor:
    plugin: make
    source: git://github.com/OpenSensorsIO/usb-thermometer
    build-packages: [libusb-dev, libudev-dev]
    
  nodejs:
    plugin: nodejs
    source: src/
